### ISSUE TITLE
Previous options to `sveltePreprocess()` overwritten.

### ISSUE THREAD

**Issue by Leftium** [svelte-add/bulma#2]
**Repro steps:**

    npm init svelte@next
    npx svelte-add postcss  # Adds options to sveltePreprocess() in svelte.config.cjs
    npx svelte-add bulma    # Rewrites sveltePreprocess() without options

It may not make sense to use these two CSS adders together, but there will be cases when multiple adders add options to sveltePreprocess(). For example, I am researching a coffeescript adder that needs to add this option to sveltePreprocess():

    preprocess: sveltePreprocess({
        coffeescript: { bare: true }
    }),

**Comment by Leftium** [comment]
Related issue: https://github.com/svelte-add/postcss/issues/17

**Comment by babichjacob** [comment]
This will be solved in a future rewrite of `svelte-add`: https://github.com/svelte-add/svelte-adders/issues/12

**Comment by bato3** [comment]
The longer I look at the code, the more pitfalls I see. We need `findCalls` and `deepMerge` method with conflict resolution. It would be better if `apply` provided them...

In current code I see couple problems:

* regex find options, but we don't merge it
* it finds first occurence `)`, so for `sveltePreproces({moo()})`...
* what happen if is coupple occurences `sveltePreprocess`? eg.: in comment

**Comment by babichjacob** [comment]
This is addressed by https://github.com/svelte-add/svelte-add/commit/82370e8d65c5deb5d1edd4a0e0a95b2ed0eeac95

I need to create an intermediate SCSS adder before the Bulma adder can be rewritten built-in to `svelte-add` such that this issue can be closed.

**Comment by babichjacob** [comment]
> I need to create an intermediate SCSS adder before the Bulma adder can be rewritten built-in to `svelte-add` such that this issue can be closed.

Closed by https://github.com/svelte-add/scss
